"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import type { QueueState, Role } from "@/lib/domain/types";
import { firebaseAuth } from "@/lib/firebase/client";
import { subscribeClinicify } from "@/lib/firebase/realtime";
import { createUserWithEmailAndPassword, onAuthStateChanged, signInWithEmailAndPassword, signOut, type User } from "firebase/auth";
import { AdminLive, BillingLive, DoctorLive, InventoryLive, PharmacyLive, ReceptionLive } from "./live-workflows";

const nav = ["Reception", "Doctor queue", "Pharmacy", "Inventory", "Billing", "Admin"] as const;
type Screen = typeof nav[number];
const departments = ["General Medicine", "Gynecology", "Pediatrics", "Radiology", "ENT", "Dentistry", "Neurology", "Cardiology", "Orthopedics", "Dermatology", "Ophthalmology", "Psychiatry"];

export function ClinicifyApp() {
  const [screen, setScreen] = useState<Screen>("Reception"); const [role, setRole] = useState<Role | null>(null); const [doctorId, setDoctorId] = useState<string>(); const [department, setDepartment] = useState<string>(); const [state, setState] = useState<QueueState>({ doctors:[], visits:[], events:[] }); const [notice, setNotice] = useState("Sign in to connect to live Clinicify data."); const [user, setUser] = useState<User | null>(null); const [loginError, setLoginError] = useState("");
  useEffect(() => onAuthStateChanged(firebaseAuth, async currentUser => { setUser(currentUser); if (!currentUser) { setRole(null); setDoctorId(undefined); setDepartment(undefined); return; } const claims = await currentUser.getIdTokenResult(true); const signedRole = claims.claims.role as Role; setRole(signedRole); setDoctorId(typeof claims.claims.doctorId === "string" ? claims.claims.doctorId : undefined); setDepartment(typeof claims.claims.department === "string" ? claims.claims.department : undefined); setScreen(signedRole === "doctor" ? "Doctor queue" : signedRole === "pharmacist" ? "Pharmacy" : signedRole === "admin" ? "Admin" : "Reception"); }), []);
  useEffect(() => { if (!user || !role) return; return subscribeClinicify(setState, { role, doctorId }); }, [user, role, doctorId]);
  const callApi = async (path: string, body?: unknown) => { if (!user) throw new Error("Please sign in."); const token = await user.getIdToken(); const response = await fetch(path, { method:body === undefined ? "GET" : "POST", headers:{ "Content-Type":"application/json", Authorization:`Bearer ${token}` }, body:body === undefined ? undefined : JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Action failed"); return result; };
  const content = useMemo(() => { if (screen === "Reception") return <ReceptionLive state={state} department={department} callApi={callApi} notify={setNotice} />; if (screen === "Doctor queue") return <DoctorLive state={state} doctorId={doctorId} callApi={callApi} notify={setNotice} />; if (screen === "Pharmacy") return <PharmacyLive role={role ?? "receptionist"} callApi={callApi} notify={setNotice} />; if (screen === "Inventory") return <InventoryLive callApi={callApi} notify={setNotice} />; if (screen === "Billing") return <BillingLive callApi={callApi} notify={setNotice} />; return <AdminLive state={state} callApi={callApi} notify={setNotice} />; }, [screen, state, department, doctorId, role, user]);
  if (!user || !role) return <Login error={loginError} onLogin={async (email, password) => { try { setLoginError(""); await signInWithEmailAndPassword(firebaseAuth, email, password); } catch { setLoginError("Unable to sign in. Check your email and password, or request access."); } }} />;
  const permitted = nav.filter(item => role === "admin" ? item === "Admin" : role === "doctor" ? item === "Doctor queue" : role === "pharmacist" ? ["Pharmacy", "Inventory", "Billing"].includes(item) : item === "Reception");
  return <main className="app"><aside className="sidebar"><a className="brand" href="#"><span>✚</span> CLINICIFY</a><p className="workspace">OPD COMMAND CENTER</p><nav>{permitted.map(item => <button key={item} className={screen === item ? "active" : ""} onClick={() => setScreen(item)}><i>{({ Reception:"⊕", "Doctor queue":"⚕", Pharmacy:"▣", Inventory:"◫", Billing:"₹", Admin:"◉" } as Record<string,string>)[item]}</i>{item}</button>)}</nav><div className="role-box"><span>Signed in as</span><strong>{role}</strong><button onClick={() => signOut(firebaseAuth)}>Sign out</button><small>Authorisation is verified by Firebase custom claims and the trusted server API.</small></div></aside><section className="workspace-main"><div className="topbar"><span className="live"><i />LIVE OPERATIONS</span><span>City General Hospital</span><button className="avatar">{user.email?.slice(0,2).toUpperCase()}</button></div>{content}</section><div className="toast">{notice}<button onClick={() => setNotice("All caught up.")}>×</button></div></main>;
}

function Login({ error, onLogin }: { error: string; onLogin: (email: string, password: string) => Promise<void> }) {
  const [role, setRole] = useState<Role | "">(""); const [request, setRequest] = useState(false); const [signIn, setSignIn] = useState(false); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [department, setDepartment] = useState("General Medicine"); const [staffId, setStaffId] = useState(""); const [name, setName] = useState(""); const [message, setMessage] = useState("");
  const submit = async (event: FormEvent) => { event.preventDefault(); try { if (signIn) return onLogin(email, password); if (!role || !staffId) throw new Error("Choose a role and enter your unique staff ID."); const credential = await createUserWithEmailAndPassword(firebaseAuth, email, password); const token = await credential.user.getIdToken(); const response = await fetch("/api/staff-requests", { method:"POST", headers:{ "Content-Type":"application/json", Authorization:`Bearer ${token}` }, body:JSON.stringify({ role, department:role === "pharmacist" ? "" : department, staffId, displayName:name }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setMessage("Request submitted. An admin must approve it before you can use the role workspace."); await signOut(firebaseAuth); } catch (issue) { setMessage(issue instanceof Error ? issue.message : "Unable to continue."); } };
  return <main className="login"><section><a className="brand" href="#"><span>✚</span> CLINICIFY</a><p className="eyebrow">Clinic operations</p><h1>{!request ? "Choose your workspace" : signIn ? "Sign in to your workspace" : "Request staff access"}</h1>{!request ? <><p>Select a workspace to request access, or sign in if you are already approved.</p><div className="role-grid">{(["admin", "doctor", "receptionist", "pharmacist"] as Role[]).map(item => <button className="doctor-choice" key={item} onClick={() => { setRole(item); setRequest(true); setSignIn(false); }}><span><b>{item[0].toUpperCase() + item.slice(1)}</b><p>Request access</p></span><b>→</b></button>)}</div><button className="secondary" onClick={() => { setRequest(true); setSignIn(true); }}>Already approved? Sign in</button></> : <form onSubmit={submit}>{signIn ? <><label>Email<input required type="email" value={email} onChange={event => setEmail(event.target.value)} /></label><label>Password<input required type="password" value={password} onChange={event => setPassword(event.target.value)} /></label></> : <><label>Requested role<select value={role} onChange={event => setRole(event.target.value as Role)}>{(["admin", "doctor", "receptionist", "pharmacist"] as Role[]).map(item => <option key={item}>{item}</option>)}</select></label><label>Full name<input required value={name} onChange={event => setName(event.target.value)} /></label><label>Email<input required type="email" value={email} onChange={event => setEmail(event.target.value)} /></label><label>Password<input required minLength={8} type="password" value={password} onChange={event => setPassword(event.target.value)} /></label>{role !== "pharmacist" && <label>Department<select value={department} onChange={event => setDepartment(event.target.value)}>{departments.map(item => <option key={item}>{item}</option>)}</select></label>}<label>Unique staff ID<input required value={staffId} onChange={event => setStaffId(event.target.value)} /></label></>}{error && <p className="form-error">{error}</p>}{message && <p className="form-error">{message}</p>}<button className="primary">{signIn ? "Sign in securely" : "Request to join"}</button><button type="button" className="secondary" onClick={() => setRequest(false)}>Back</button></form>}</section><aside><p className="eyebrow">Live, role-based care</p><h2>Reception → Doctor → Prescription → Pharmacy</h2><p>Every patient and room update is shared in real time after authorised sign-in.</p></aside></main>;
}
