"use client";
import { useMemo, useState } from "react";
import { initialState } from "@/lib/demo-data";
import { insertPriority } from "@/lib/domain/queue";
import type { Doctor, QueueState, Role, Visit } from "@/lib/domain/types";

const nav = ["Overview", "Reception", "Doctor queue", "Pharmacy", "Inventory", "Billing", "Admin"] as const;
type Screen = typeof nav[number] | "Tracking";
const clock = (value?: number) => value ? new Intl.DateTimeFormat("en-IN", { hour: "numeric", minute: "2-digit" }).format(value) : "—";
const waiting = (state: QueueState, doctorId?: string) => state.visits.filter(v => v.status === "waiting" && (!doctorId || v.doctorId === doctorId));

function StatusBadge({ label }: { label: string }) { return <span className={`badge ${label.toLowerCase().replaceAll(" ", "-")}`}>{label.replaceAll("_", " ")}</span>; }
function MetricCard({ label, value, note }: { label: string; value: string; note: string }) { return <article className="metric"><span>{label}</span><strong>{value}</strong><small>{note}</small></article>; }
function PageHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <header className="page-header"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div>{action}</header>; }
function QueueCard({ doctor, state }: { doctor: Doctor; state: QueueState }) { const list = waiting(state, doctor.id); return <article className="queue-card"><div className="queue-top"><div><h3>{doctor.name}</h3><p>{doctor.department} · {doctor.room}</p></div><StatusBadge label={doctor.status} /></div><div className="queue-summary"><strong>{list.length}</strong><span>waiting</span><span>~{list.reduce((total, v) => total + v.predictedDuration + 2, 0)} min clearance</span></div><div className="timeline">{list.length ? list.map(v => <div className={`queue-row ${v.priorityLevel ? "priority-row" : ""}`} key={v.id}><b>{v.token}</b><span>{v.priorityLevel ? "Priority consultation" : v.complaint}</span><em>{clock(v.etaLower)}–{clock(v.etaUpper)}</em></div>) : <div className="empty-inline">No waiting patients</div>}</div></article>; }

export function ClinicifyApp() {
  const [screen, setScreen] = useState<Screen>("Overview"); const [role, setRole] = useState<Role>("receptionist"); const [state, setState] = useState(initialState); const [notice, setNotice] = useState("Live queue data is connected in demo mode.");
  const mehta = state.doctors[0]; const current = state.visits.find(v => v.id === mehta.currentVisitId);
  const priority = () => { const v: Visit = { id: `v-e-${Date.now()}`, patientId: "p-demo-priority", patientName: "Priority patient", age: 46, token: "E-04", doctorId: mehta.id, complaint: "Authorized priority case", complaintCategory: "injury", priorityLevel: 0, sequenceNumber: 0, status: "waiting", predictedDuration: 14 }; setState(s => insertPriority(s, v, mehta.id)); setNotice("Priority case inserted in Dr. Mehta’s queue. Downstream ETAs were reforecast; Dr. Iyer is unchanged."); };
  const patientsAhead = waiting(state, mehta.id).findIndex(v => v.token === "GM-080");
  const content = useMemo(() => {
    if (screen === "Reception") return <Reception state={state} onConfirm={() => setNotice("Visit GM-083 created. Token confirmation email queued independently from queue state.")} />;
    if (screen === "Doctor queue") return <DoctorView state={state} current={current} />;
    if (screen === "Pharmacy") return <Pharmacy />;
    if (screen === "Inventory") return <Inventory />;
    if (screen === "Billing") return <Billing />;
    if (screen === "Admin") return <Admin state={state} />;
    if (screen === "Tracking") return <Tracking state={state} ahead={patientsAhead} />;
    return <Overview state={state} onPriority={priority} onTrack={() => setScreen("Tracking")} />;
  }, [screen, state, current, patientsAhead]);
  return <main className="app"><aside className="sidebar"><a className="brand" href="#"><span>✚</span> CLINICIFY</a><p className="workspace">OPD COMMAND CENTER</p><nav>{nav.map(item => <button key={item} className={screen === item ? "active" : ""} onClick={() => setScreen(item)}><i>{icon(item)}</i>{item}</button>)}</nav><div className="role-box"><span>Signed in as</span><strong>{role}</strong><select aria-label="Demo role preview" value={role} onChange={e => setRole(e.target.value as Role)}><option value="receptionist">Receptionist</option><option value="doctor">Doctor</option><option value="pharmacist">Pharmacist</option><option value="admin">Admin</option></select><small>Demo UI only — server role authorization is required in production.</small></div></aside><section className="workspace-main"><div className="topbar"><span className="live"><i />LIVE OPERATIONS</span><span>City General Hospital · Friday, 19 September</span><button className="avatar">RM</button></div>{content}</section><div className="toast">{notice}<button onClick={() => setNotice("All caught up.")}>×</button></div></main>;
}
function icon(name: string) { return ({ Overview: "⌂", Reception: "⊕", "Doctor queue": "⚕", Pharmacy: "▣", Inventory: "◫", Billing: "₹", Admin: "◉" } as Record<string, string>)[name] ?? ""; }

function Overview({ state, onPriority, onTrack }: { state: QueueState; onPriority: () => void; onTrack: () => void }) { return <><PageHeader eyebrow="Hospital Operations" title="Good morning, Reception" description="Keep today’s OPD moving with live queue intelligence." action={<button className="primary">+ Register patient</button>} /><div className="metrics"><MetricCard label="Registered today" value="86" note="↑ 12% from yesterday"/><MetricCard label="Currently waiting" value={String(waiting(state).length)} note="Across 3 active doctors"/><MetricCard label="Doctors available" value="8" note="2 additional doctors paused"/><MetricCard label="Average estimated wait" value="24 min" note="↓ 4 min from baseline"/></div><section className="feature"><div><p className="eyebrow">Live queue intelligence</p><h2>Priority reforecast demo</h2><p>Insert an authorized priority case into Dr. Mehta’s queue. Only that doctor’s downstream ETA changes.</p></div><button className="priority-button" onClick={onPriority}>+ Add priority case</button></section><div className="queue-grid">{state.doctors.slice(0,2).map(d => <QueueCard key={d.id} doctor={d} state={state} />)}</div><section className="two-col"><article className="panel"><div className="panel-head"><h2>Today’s activity</h2><button>View all</button></div><div className="activity"><p><b>GM-083</b> registered with Dr. Mehta <time>2 min ago</time></p><p><b>Prescription saved</b> for visit GM-076 <time>11 min ago</time></p><p><b>Pharmacy order ready</b> · token OR-021 <time>16 min ago</time></p></div></article><article className="panel patient-preview"><p className="eyebrow">Patient experience</p><h2>Share a live tracking link</h2><p>Patients see their token, ETA range and recommended arrival—without an account.</p><button className="secondary" onClick={onTrack}>Preview patient tracking →</button></article></section></> }

function Reception({ state, onConfirm }: { state: QueueState; onConfirm: () => void }) { return <><PageHeader eyebrow="Reception workstation" title="Register a patient" description="Create a visit, choose a doctor and generate a doctor-specific smart token." /><div className="reception-grid"><section className="panel form"><h2>Patient lookup</h2><label>Mobile number or hospital patient ID<input placeholder="Search patient records" defaultValue="98765 43210" /></label><div className="returning"><span>✓</span><div><b>Returning patient found</b><p>Meera Joshi · Patient ID P-10028</p></div><button>Change</button></div><h2>Visit details</h2><div className="fields"><label>Full name<input defaultValue="Meera Joshi" /></label><label>Age<input defaultValue="28" /></label><label>Department<select defaultValue="General Medicine"><option>General Medicine</option><option>Orthopedics</option></select></label><label>Complaint category<select><option>Headache</option><option>Fever</option><option>Follow-up</option></select></label></div><label>Reason for visit<textarea defaultValue="Persistent headache for two days" /></label></section><section className="panel"><div className="panel-head"><div><h2>Select doctor</h2><p>Choose the operationally suitable doctor.</p></div><StatusBadge label="2 available" /></div>{state.doctors.slice(0,2).map((d, i) => <div className={`doctor-choice ${i === 0 ? "selected" : ""}`} key={d.id}><div className="doctor-avatar">{d.name.split(" ").at(-1)?.[0]}</div><div><b>{d.name}</b><p>{d.department} · {d.room}</p><StatusBadge label={d.status} /></div><div className="doctor-wait"><b>{waiting(state, d.id).length} waiting</b><span>~{waiting(state, d.id).reduce((s, v) => s + v.predictedDuration, 0)} min</span></div></div>)}<button className="primary wide" onClick={onConfirm}>Create visit & generate token →</button><div className="confirmation"><span className="check">✓</span><div><p>Token preview</p><h3>GM-083</h3><small>Expected consultation: 2:20 PM – 2:35 PM</small></div></div></section></div></> }

function DoctorView({ state, current }: { state: QueueState; current?: Visit }) { return <><PageHeader eyebrow="Doctor workspace" title="Dr. Ananya Mehta" description="General Medicine · Room 3" action={<button className="secondary">Pause queue</button>} /><div className="metrics"><MetricCard label="Current patient" value={current?.token ?? "—"} note="Consultation in progress"/><MetricCard label="Waiting" value={String(waiting(state, "d-mehta").length)} note="1 priority case possible"/><MetricCard label="Average consultation" value="9 min" note="Today’s observed average"/><MetricCard label="Queue clearance" value="32 min" note="Estimated from live workload"/></div><div className="doctor-layout"><article className="current-card"><p className="eyebrow">Current patient</p><div className="token-circle">{current?.token}</div><h2>{current?.patientName}</h2><p>{current?.age} years · {current?.complaint}</p><div className="timer">00:03:14 <span>consultation active</span></div><button className="primary">Complete consultation</button><button className="link-button">Open prescription builder →</button></article><article className="panel"><div className="panel-head"><h2>Upcoming queue</h2><span>{waiting(state, "d-mehta").length} patients</span></div>{waiting(state, "d-mehta").map(v => <div className="upcoming" key={v.id}><b>{v.token}</b><div><strong>{v.patientName}</strong><p>{v.complaint}</p></div>{v.priorityLevel ? <StatusBadge label="Priority"/> : <span>{clock(v.etaLower)}</span>}</div>)}</article></div></> }

function Pharmacy() { const orders = [["GM-076", "Paracetamol, 2 items", "Received"], ["OR-021", "Diclofenac, 1 item", "Preparing"], ["GM-068", "Amoxicillin, 3 items", "Ready"]]; return <><PageHeader eyebrow="Pharmacy" title="Prescription fulfillment" description="Track and dispense orders linked to the visit." action={<button className="secondary">Search token / visit</button>}/><div className="metrics"><MetricCard label="New prescriptions" value="8" note="Since 8:00 AM"/><MetricCard label="Preparing" value="5" note="Average 7 min turnaround"/><MetricCard label="Ready" value="4" note="Notify patients"/><MetricCard label="Low stock" value="3" note="Review inventory"/></div><section className="panel"><div className="tabs"><b>New <span>8</span></b><span>Preparing</span><span>Ready</span><span>Dispensed</span></div><table><thead><tr><th>Token</th><th>Prescription</th><th>Doctor</th><th>Received</th><th>Status</th><th></th></tr></thead><tbody>{orders.map(o => <tr key={o[0]}><td><b>{o[0]}</b></td><td>{o[1]}</td><td>Dr. Mehta</td><td>10 min ago</td><td><StatusBadge label={o[2]}/></td><td><button className="table-action">Open →</button></td></tr>)}</tbody></table></section></> }
function Inventory() { return <><PageHeader eyebrow="Pharmacy management" title="Medicine inventory" description="Exact stock is visible only to pharmacy and authorised administrators." action={<button className="primary">+ Adjust stock</button>}/><section className="panel"><input className="search" placeholder="Search medicines"/><table><thead><tr><th>Medicine</th><th>Stock</th><th>Status</th><th>Unit price</th><th>Last updated</th></tr></thead><tbody>{[["Paracetamol 500mg","342","Available","₹1.20"],["Amoxicillin 250mg","18","Low stock","₹4.50"],["Diclofenac gel","0","Out of stock","₹62.00"]].map(r => <tr key={r[0]}><td><b>{r[0]}</b></td><td>{r[1]}</td><td><StatusBadge label={r[2]}/></td><td>{r[3]}</td><td>Today, 11:42 AM</td></tr>)}</tbody></table></section></> }
function Billing() { return <><PageHeader eyebrow="Billing" title="Visit-linked billing" description="Search by a visit ID or token; no-charge and subsidised medicines are supported."/><section className="panel bill"><input className="search" defaultValue="GM-076"/><div className="bill-inner"><div><p className="eyebrow">Visit GM-076</p><h2>Prescription invoice</h2><p>2 medicines · Pharmacy order dispensed</p></div><div className="bill-amount"><small>Total payable</small><strong>₹84.00</strong><StatusBadge label="Pending"/></div></div><div className="bill-lines"><span>Paracetamol 500mg × 10 <b>₹12.00</b></span><span>Amoxicillin 250mg × 16 <b>₹72.00</b></span></div><div className="bill-actions"><button className="secondary">Mark no charge</button><button className="primary">Record payment</button></div></section></> }
function Admin({ state }: { state: QueueState }) { return <><PageHeader eyebrow="Administration" title="Hospital operations" description="A concise, real-time picture of OPD flow and service quality."/><div className="metrics"><MetricCard label="OPD visits today" value="86" note="12 more than yesterday"/><MetricCard label="Currently waiting" value={String(waiting(state).length)} note="Across all departments"/><MetricCard label="Priority cases" value={String(state.events.filter(e => e.type === "PRIORITY_INSERTED").length + 2)} note="All events auditable"/><MetricCard label="Pharmacy pending" value="13" note="Average turnaround: 9 min"/></div><section className="panel"><div className="panel-head"><div><h2>Doctor operations</h2><p>Live queue load and clearance forecast</p></div><button>View queue events</button></div><table><thead><tr><th>Doctor</th><th>Status</th><th>Current token</th><th>Waiting</th><th>Average consultation</th><th>Clearance</th></tr></thead><tbody>{state.doctors.map(d => <tr key={d.id}><td><b>{d.name}</b><small>{d.department}</small></td><td><StatusBadge label={d.status}/></td><td>{state.visits.find(v => v.id === d.currentVisitId)?.token ?? "—"}</td><td>{waiting(state,d.id).length}</td><td>{d.averageDuration} min</td><td>~{waiting(state,d.id).reduce((n,v)=>n+v.predictedDuration+2,0)} min</td></tr>)}</tbody></table></section></> }
function Tracking({ state, ahead }: { state: QueueState; ahead: number }) { const v = state.visits.find(x => x.token === "GM-080")!; return <div className="tracking"><header><a className="brand" href="#"><span>✚</span> CLINICIFY</a><button>Need help?</button></header><main><p className="eyebrow">Your OPD visit</p><h1>{v.token}</h1><p className="tracking-doctor">Dr. Ananya Mehta · General Medicine</p><div className="track-status"><span className="pulse"/> QUEUE STATUS · WAITING</div><section className="eta-card"><p>Expected consultation</p><h2>{clock(v.etaLower)} – {clock(v.etaUpper)}</h2><span>Recommended arrival <b>{clock(v.recommendedArrival)}</b></span></section><div className="progress"><div><span>Patients ahead</span><b>{Math.max(ahead, 0)}</b></div><div className="progress-bar"><i style={{width: `${Math.max(20, 70 - Math.max(ahead, 0) * 15)}%`}}/></div><small>Your queue position updates live.</small></div>{state.events.some(e=>e.type === "PRIORITY_INSERTED") && <aside className="priority-note"><b>Queue updated</b><p>A priority case has affected your doctor’s queue. Your expected consultation time has been updated.</p></aside>}<p className="last-updated">Last updated just now · This page refreshes automatically</p></main></div> }
