"use client";
import { useEffect, useMemo, useState } from "react";
import type * as React from "react";
import { collection, onSnapshot } from "firebase/firestore";
import { firestore } from "@/lib/firebase/client";
import type { Doctor, QueueState, Role } from "@/lib/domain/types";

type CallApi = (path: string, body: unknown) => Promise<unknown>;
type Notice = (text: string) => void;
type RecordDoc = { id: string; [key: string]: unknown };
const waiting = (s: QueueState, d?: string) => s.visits.filter(v => v.status === "waiting" && (!d || v.doctorId === d));
const fmt = (value?: number) => value ? new Intl.DateTimeFormat("en-IN", { hour: "numeric", minute: "2-digit" }).format(value) : "—";
function useRecords(name: string) { const [rows, setRows] = useState<RecordDoc[]>([]); useEffect(() => onSnapshot(collection(firestore, name), snap => setRows(snap.docs.map(doc => ({ id: doc.id, ...doc.data() }))), () => setRows([])), [name]); return rows; }
function run(call: CallApi, notify: Notice, action: string, body: unknown) { return call(`/api/operations/${action}`, body).then(() => notify(`${action.replaceAll("-", " ")} saved successfully.`)).catch(e => notify(e instanceof Error ? e.message : "Operation failed.")); }

export function ReceptionLive({ state, callApi, notify }: { state: QueueState; callApi: CallApi; notify: Notice }) { const [form, setForm] = useState({ name: "", age: "", mobile: "", email: "", complaint: "", complaintCategory: "general", doctorId: state.doctors[0]?.id ?? "" }); const [created, setCreated] = useState<{ token: string; trackingUrl: string }>(); const doctors = state.doctors.filter(d => d.department === "General Medicine"); const change = (key: keyof typeof form, value: string) => setForm(s => ({ ...s, [key]: value })); const submit = async (e: React.FormEvent) => { e.preventDefault(); try { const r = await callApi("/api/visits", { patient: { name: form.name, age: Number(form.age), mobile: form.mobile, email: form.email || undefined }, doctorId: form.doctorId, complaint: form.complaint, complaintCategory: form.complaintCategory, departmentId: "general-medicine" }) as { token: string; trackingUrl: string }; setCreated(r); notify(`Visit ${r.token} created and queued.`); } catch (err) { notify(err instanceof Error ? err.message : "Visit creation failed."); } };
  return <><header className="page-header"><div><p className="eyebrow">Reception workstation</p><h1>Register patient</h1><p>Register a new or returning patient, select their doctor, and issue a live smart token.</p></div></header><div className="reception-grid"><form className="panel form" onSubmit={submit}><label>Mobile number / hospital ID<input required value={form.mobile} onChange={e=>change("mobile",e.target.value)} placeholder="Search or enter a synthetic mobile number" /></label><div className="fields"><label>Full name<input required value={form.name} onChange={e=>change("name",e.target.value)} /></label><label>Age<input required min="0" type="number" value={form.age} onChange={e=>change("age",e.target.value)} /></label><label>Email (optional)<input type="email" value={form.email} onChange={e=>change("email",e.target.value)} /></label><label>Complaint category<select value={form.complaintCategory} onChange={e=>change("complaintCategory",e.target.value)}><option value="general">General</option><option value="fever">Fever</option><option value="headache">Headache</option><option value="injury">Injury</option><option value="follow_up">Follow-up</option></select></label></div><label>Reason for visit<textarea required value={form.complaint} onChange={e=>change("complaint",e.target.value)} /></label><button className="primary" type="submit">Create visit & token →</button></form><section className="panel"><h2>Select doctor</h2>{doctors.map(d => <button type="button" className={`doctor-choice ${form.doctorId === d.id ? "selected" : ""}`} key={d.id} onClick={()=>change("doctorId",d.id)}><div><b>{d.name}</b><p>{d.room} · {d.status}</p></div><div className="doctor-wait"><b>{waiting(state,d.id).length} waiting</b><span>~{waiting(state,d.id).reduce((n,v)=>n+v.predictedDuration+2,0)} min</span></div></button>)}{created && <div className="confirmation"><span className="check">✓</span><div><p>Token issued</p><h3>{created.token}</h3><a href={created.trackingUrl} target="_blank">Open secure patient tracking →</a></div></div>}</section></div></> }

export function DoctorLive({ state, doctorId, callApi, notify }: { state: QueueState; doctorId?: string; callApi: CallApi; notify: Notice }) { const doctor = state.doctors.find(d=>d.id===doctorId) ?? state.doctors[0]; const current = state.visits.find(v=>v.id===doctor?.currentVisitId); const queue = waiting(state,doctor?.id); const [notes,setNotes]=useState(""); if (!doctor) return null; const act = (name:string, body:object) => void run(callApi,notify,name,body); return <><header className="page-header"><div><p className="eyebrow">Doctor workspace</p><h1>{doctor.name}</h1><p>{doctor.department} · {doctor.room}</p></div><button className="secondary" onClick={()=>act("pause",{doctorId:doctor.id,paused:doctor.status!=="paused"})}>{doctor.status === "paused" ? "Resume queue" : "Pause queue"}</button></header><div className="doctor-layout"><section className="current-card"><p className="eyebrow">Current patient</p><div className="token-circle">{current?.token ?? queue[0]?.token ?? "—"}</div><h2>{current?.patientName ?? queue[0]?.patientName ?? "No waiting patient"}</h2><p>{current?.complaint ?? queue[0]?.complaint}</p><textarea placeholder="Clinical notes (saved with prescription workflow)" value={notes} onChange={e=>setNotes(e.target.value)}/><button className="primary" onClick={()=>act(current?"complete":"start",{visitId:current?.id ?? queue[0]?.id,doctorId:doctor.id})}>{current?"Complete consultation":"Start consultation"}</button>{(current ?? queue[0]) && <button className="link-button" onClick={()=>act("prescription",{visitId:(current??queue[0]).id,doctorId:doctor.id,notes,items:[{medicineId:"m-paracetamol",name:"Paracetamol 500mg",dosage:"500 mg",frequency:"Twice daily",timing:"After food",duration:"3 days",quantity:6,notes}]})}>Save prescription →</button>}</section><section className="panel"><h2>Live queue</h2>{queue.map(v=><div className="upcoming" key={v.id}><b>{v.token}</b><div><strong>{v.patientName}</strong><p>{v.complaint}</p></div><span>{fmt(v.etaLower)}</span><button className="table-action" onClick={()=>act("no-show",{visitId:v.id})}>No-show</button></div>)}</section></div></> }

export function PharmacyLive({ role, callApi, notify }: { role: Role; callApi: CallApi; notify: Notice }) { const orders=useRecords("pharmacyOrders"); return <><header className="page-header"><div><p className="eyebrow">Pharmacy</p><h1>Prescription fulfillment</h1><p>Live pharmacy orders are linked to visit IDs and protected by pharmacy roles.</p></div></header><section className="panel"><table><thead><tr><th>Token</th><th>Order</th><th>Status</th><th>Billing</th><th>Actions</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{String(o.token ?? "—")}</td><td>{o.id.slice(0,8)}</td><td>{String(o.status)}</td><td>{String(o.billingStatus ?? "pending")}</td><td><button className="table-action" onClick={()=>void run(callApi,notify,"pharmacy-status",{orderId:o.id,status:"preparing"})}>Prepare</button><button className="table-action" onClick={()=>void run(callApi,notify,"pharmacy-status",{orderId:o.id,status:"ready"})}>Ready</button><button className="table-action" onClick={()=>void run(callApi,notify,"pharmacy-status",{orderId:o.id,status:"dispensed"})}>Dispense</button></td></tr>)}</tbody></table>{!orders.length&&<p>No prescriptions yet. Doctors create the first pharmacy order.</p>}</section></> }

export function InventoryLive({ callApi, notify }: { callApi: CallApi; notify: Notice }) { const meds=useRecords("medicines"); return <><header className="page-header"><div><p className="eyebrow">Inventory</p><h1>Medicine stock</h1><p>Exact stock is available to pharmacy/admin only.</p></div></header><section className="panel"><table><thead><tr><th>Medicine</th><th>Stock</th><th>Status</th><th>Unit price</th><th>Adjust</th></tr></thead><tbody>{meds.map(m=><tr key={m.id}><td>{String(m.name)}</td><td>{String(m.stockQuantity)}</td><td>{String(m.stockStatus)}</td><td>₹{String(m.unitPrice)}</td><td><button className="table-action" onClick={()=>void run(callApi,notify,"inventory",{medicineId:m.id,delta:-1})}>−1</button><button className="table-action" onClick={()=>void run(callApi,notify,"inventory",{medicineId:m.id,delta:1})}>+1</button></td></tr>)}</tbody></table></section></> }

export function BillingLive({ callApi, notify }: { callApi: CallApi; notify: Notice }) { const orders=useRecords("pharmacyOrders"); return <><header className="page-header"><div><p className="eyebrow">Billing</p><h1>Visit-linked billing</h1><p>Paid, pending and no-charge orders are supported.</p></div></header><section className="panel"><table><thead><tr><th>Token</th><th>Order</th><th>Total</th><th>Billing state</th><th>Set state</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{String(o.token??"—")}</td><td>{o.id.slice(0,8)}</td><td>₹{String(o.total??0)}</td><td>{String(o.billingStatus??"pending")}</td><td><button className="table-action" onClick={()=>void run(callApi,notify,"billing",{orderId:o.id,billingStatus:"paid"})}>Paid</button><button className="table-action" onClick={()=>void run(callApi,notify,"billing",{orderId:o.id,billingStatus:"free"})}>No charge</button></td></tr>)}</tbody></table></section></> }

export function AdminLive({ state }: { state: QueueState }) { const orders=useRecords("pharmacyOrders"); const avg=useMemo(()=>{const values=state.visits.filter(v=>v.etaUpper&&v.etaLower).map(v=>((v.etaUpper??0)-(v.etaLower??0))/60000); return values.length?Math.round(values.reduce((a,b)=>a+b,0)/values.length):8;},[state]); return <><header className="page-header"><div><p className="eyebrow">Administration</p><h1>Hospital operations</h1><p>Live queue load, audit activity and workflow backlog.</p></div></header><div className="metrics"><article className="metric"><span>Visits</span><strong>{state.visits.length}</strong><small>Live Firestore count</small></article><article className="metric"><span>Waiting</span><strong>{waiting(state).length}</strong><small>Across active queues</small></article><article className="metric"><span>Average ETA range</span><strong>{avg} min</strong><small>Deterministic demo baseline</small></article><article className="metric"><span>Pharmacy pending</span><strong>{orders.filter(o=>o.status!=="dispensed").length}</strong><small>Live order count</small></article></div><section className="panel"><h2>Auditable queue events</h2>{state.events.slice(-12).reverse().map(e=><p className="activity" key={e.id}><b>{e.type}</b> · {e.visitId || "hospital operation"}</p>)}</section></> }
